package com.ump.entity;

import com.eparking.util.ExcelTitle;

/**
 * @Author lishuhan
 * @Description:
 * @Date Create in 18:122018-12-10
 * @Modified By:
 */
public class ExcelTParkDuty {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_duty.actual_total
     *
     * @mbg.generated
     */
    private Double actualTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_duty.begin_time
     *
     * @mbg.generated
     */
    private String beginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_duty.duty_person
     *
     * @mbg.generated
     */
    private String dutyPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_duty.end_time
     *
     * @mbg.generated
     */
    private String endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_duty.free_pass
     *
     * @mbg.generated
     */
    private Integer freePass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_duty.last_charge_time
     *
     * @mbg.generated
     */
    private String lastChargeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_duty.manual_pass
     *
     * @mbg.generated
     */
    private Integer manualPass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_duty.match_pass
     *
     * @mbg.generated
     */
    private Integer matchPass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_duty.need_total
     *
     * @mbg.generated
     */
    private Double needTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_duty.pay_online_total
     *
     * @mbg.generated
     */
    private Double payOnlineTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_duty.sys_pass
     *
     * @mbg.generated
     */
    private Integer sysPass;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_duty.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_duty.prepay_total
     *
     * @mbg.generated
     */
    private Double prepayTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_duty.qpasspay_total
     *
     * @mbg.generated
     */
    private Double qpasspayTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_duty.behalfpay_total
     *
     * @mbg.generated
     */
    private Double behalfpayTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_duty.noconfirm_pass
     *
     * @mbg.generated
     */
    private Integer noconfirmPass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_duty.localcoupon_total
     *
     * @mbg.generated
     */
    private Double localcouponTotal;

    @ExcelTitle(value = "实收金额",order=1)
    public Double getActualTotal() {
        return actualTotal;
    }

    public void setActualTotal(Double actualTotal) {
        this.actualTotal = actualTotal;
    }
    @ExcelTitle(value = "当班时间",order=2)
    public String getBeginTime() {
        return beginTime;
    }

    public void setBeginTime(String beginTime) {
        this.beginTime = beginTime;
    }
    @ExcelTitle(value = "当班员",order=3)
    public String getDutyPerson() {
        return dutyPerson;
    }

    public void setDutyPerson(String dutyPerson) {
        this.dutyPerson = dutyPerson;
    }
    @ExcelTitle(value = "交班时间",order=4)
    public String getEndTime() {
        return endTime;
    }

    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }
    @ExcelTitle(value = "免费放行次数",order=5)
    public Integer getFreePass() {
        return freePass;
    }

    public void setFreePass(Integer freePass) {
        this.freePass = freePass;
    }
    @ExcelTitle(value = "最后一笔收费时间",order=6)
    public String getLastChargeTime() {
        return lastChargeTime;
    }

    public void setLastChargeTime(String lastChargeTime) {
        this.lastChargeTime = lastChargeTime;
    }
    @ExcelTitle(value = "手动放行次数",order=7)
    public Integer getManualPass() {
        return manualPass;
    }

    public void setManualPass(Integer manualPass) {
        this.manualPass = manualPass;
    }
    @ExcelTitle(value = "人工匹配次数",order=8)
    public Integer getMatchPass() {
        return matchPass;
    }

    public void setMatchPass(Integer matchPass) {
        this.matchPass = matchPass;
    }
    @ExcelTitle(value = "应收总额",order=9)
    public Double getNeedTotal() {
        return needTotal;
    }

    public void setNeedTotal(Double needTotal) {
        this.needTotal = needTotal;
    }
    @ExcelTitle(value = "线上支付总额",order=10)
    public Double getPayOnlineTotal() {
        return payOnlineTotal;
    }

    public void setPayOnlineTotal(Double payOnlineTotal) {
        this.payOnlineTotal = payOnlineTotal;
    }
    @ExcelTitle(value = "系统放行次数",order=11)
    public Integer getSysPass() {
        return sysPass;
    }

    public void setSysPass(Integer sysPass) {
        this.sysPass = sysPass;
    }
    @ExcelTitle(value = "岗亭",order=12)
    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }
    @ExcelTitle(value = "预缴总计",order=13)
    public Double getPrepayTotal() {
        return prepayTotal;
    }

    public void setPrepayTotal(Double prepayTotal) {
        this.prepayTotal = prepayTotal;
    }
    @ExcelTitle(value = "闪付总计",order=14)
    public Double getQpasspayTotal() {
        return qpasspayTotal;
    }

    public void setQpasspayTotal(Double qpasspayTotal) {
        this.qpasspayTotal = qpasspayTotal;
    }
    @ExcelTitle(value = "代缴总计",order=15)
    public Double getBehalfpayTotal() {
        return behalfpayTotal;
    }

    public void setBehalfpayTotal(Double behalfpayTotal) {
        this.behalfpayTotal = behalfpayTotal;
    }
    @ExcelTitle(value = "未确认放行次数",order=16)
    public Integer getNoconfirmPass() {
        return noconfirmPass;
    }

    public void setNoconfirmPass(Integer noconfirmPass) {
        this.noconfirmPass = noconfirmPass;
    }
    @ExcelTitle(value = "线下减免",order=17)
    public Double getLocalcouponTotal() {
        return localcouponTotal;
    }

    public void setLocalcouponTotal(Double localcouponTotal) {
        this.localcouponTotal = localcouponTotal;
    }
}
