package com.ump.entity;

import com.eparking.util.ExcelTitle;

/**
 * @Author lishuhan
 * @Description:
 * @Date Create in 15:512018-12-11
 * @Modified By:
 */
public class ExeclParkReportYear {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_report.create_date
     *
     * @mbg.generated
     */
    private String createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_report.temp_cash_need_total
     *
     * @mbg.generated
     */
    private Double tempCashNeedTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_report.temp_cash_actual_total
     *
     * @mbg.generated
     */
    private Double tempCashActualTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_report.temp_online_need_total
     *
     * @mbg.generated
     */
    private Double tempOnlineNeedTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_report.temp_online_total
     *
     * @mbg.generated
     */
    private Double tempOnlineTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_report.fix_add
     *
     * @mbg.generated
     */
    private Integer fixAdd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_report.fix_cash_need_total
     *
     * @mbg.generated
     */
    private Double fixCashNeedTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_report.fix_cash_actual_total
     *
     * @mbg.generated
     */
    private Double fixCashActualTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_report.fix_online_need_total
     *
     * @mbg.generated
     */
    private Double fixOnlineNeedTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_report.fix_online_actual_total
     *
     * @mbg.generated
     */
    private Double fixOnlineActualTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_report.center_charge_total
     *
     * @mbg.generated
     */
    private Double centerChargeTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_report.business_circle_total
     *
     * @mbg.generated
     */
    private Double businessCircleTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_report.free_total
     *
     * @mbg.generated
     */
    private Integer freeTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_report.temp_NeedPay_Total
     *
     * @mbg.generated
     */
    private Double tempNeedpayTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_report.temp_BehalfPay_Total
     *
     * @mbg.generated
     */
    private Double tempBehalfpayTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_report.temp_qPassPay_Total
     *
     * @mbg.generated
     */
    private Double tempQpasspayTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_report.temp_PrePay_Total
     *
     * @mbg.generated
     */
    private Double tempPrepayTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_report.temp_Pay_diff
     *
     * @mbg.generated
     */
    private Double tempPayDiff;


    @ExcelTitle(value = "账单日期",order=1)
    public String getCreateDate() {
        return createDate;
    }

    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }
    @ExcelTitle(value = "临时车现金应收",order=2)
    public Double getTempCashNeedTotal() {
        return tempCashNeedTotal;
    }

    public void setTempCashNeedTotal(Double tempCashNeedTotal) {
        this.tempCashNeedTotal = tempCashNeedTotal;
    }
    @ExcelTitle(value = "临时车现金实收",order=3)
    public Double getTempCashActualTotal() {
        return tempCashActualTotal;
    }

    public void setTempCashActualTotal(Double tempCashActualTotal) {
        this.tempCashActualTotal = tempCashActualTotal;
    }
    @ExcelTitle(value = "临时车电子支付应收",order=4)
    public Double getTempOnlineNeedTotal() {
        return tempOnlineNeedTotal;
    }

    public void setTempOnlineNeedTotal(Double tempOnlineNeedTotal) {
        this.tempOnlineNeedTotal = tempOnlineNeedTotal;
    }
    @ExcelTitle(value = "临时车电子支付实收",order=5)
    public Double getTempOnlineTotal() {
        return tempOnlineTotal;
    }

    public void setTempOnlineTotal(Double tempOnlineTotal) {
        this.tempOnlineTotal = tempOnlineTotal;
    }
    @ExcelTitle(value = "新增月租车辆",order=6)
    public Integer getFixAdd() {
        return fixAdd;
    }

    public void setFixAdd(Integer fixAdd) {
        this.fixAdd = fixAdd;
    }
    @ExcelTitle(value = "月租车现金应收",order=7)
    public Double getFixCashNeedTotal() {
        return fixCashNeedTotal;
    }

    public void setFixCashNeedTotal(Double fixCashNeedTotal) {
        this.fixCashNeedTotal = fixCashNeedTotal;
    }
    @ExcelTitle(value = "月租车现金实收",order=8)
    public Double getFixCashActualTotal() {
        return fixCashActualTotal;
    }

    public void setFixCashActualTotal(Double fixCashActualTotal) {
        this.fixCashActualTotal = fixCashActualTotal;
    }
    @ExcelTitle(value = "月租车电子支付应收",order=9)
    public Double getFixOnlineNeedTotal() {
        return fixOnlineNeedTotal;
    }

    public void setFixOnlineNeedTotal(Double fixOnlineNeedTotal) {
        this.fixOnlineNeedTotal = fixOnlineNeedTotal;
    }
    @ExcelTitle(value = "月租车电子支付实收",order=10)
    public Double getFixOnlineActualTotal() {
        return fixOnlineActualTotal;
    }

    public void setFixOnlineActualTotal(Double fixOnlineActualTotal) {
        this.fixOnlineActualTotal = fixOnlineActualTotal;
    }
    @ExcelTitle(value = "中央收费总额",order=11)
    public Double getCenterChargeTotal() {
        return centerChargeTotal;
    }

    public void setCenterChargeTotal(Double centerChargeTotal) {
        this.centerChargeTotal = centerChargeTotal;
    }
    @ExcelTitle(value = "商圈收费总额",order=12)
    public Double getBusinessCircleTotal() {
        return businessCircleTotal;
    }

    public void setBusinessCircleTotal(Double businessCircleTotal) {
        this.businessCircleTotal = businessCircleTotal;
    }
    @ExcelTitle(value = "免费车数量",order=13)
    public Integer getFreeTotal() {
        return freeTotal;
    }

    public void setFreeTotal(Integer freeTotal) {
        this.freeTotal = freeTotal;
    }
    @ExcelTitle(value = "总应收",order=14)
    public Double getTempNeedpayTotal() {
        return tempNeedpayTotal;
    }

    public void setTempNeedpayTotal(Double tempNeedpayTotal) {
        this.tempNeedpayTotal = tempNeedpayTotal;
    }
    @ExcelTitle(value = "总代缴",order=15)
    public Double getTempBehalfpayTotal() {
        return tempBehalfpayTotal;
    }

    public void setTempBehalfpayTotal(Double tempBehalfpayTotal) {
        this.tempBehalfpayTotal = tempBehalfpayTotal;
    }
    @ExcelTitle(value = "总闪付",order=16)
    public Double getTempQpasspayTotal() {
        return tempQpasspayTotal;
    }

    public void setTempQpasspayTotal(Double tempQpasspayTotal) {
        this.tempQpasspayTotal = tempQpasspayTotal;
    }
    @ExcelTitle(value = "总预缴",order=17)
    public Double getTempPrepayTotal() {
        return tempPrepayTotal;
    }

    public void setTempPrepayTotal(Double tempPrepayTotal) {
        this.tempPrepayTotal = tempPrepayTotal;
    }
    @ExcelTitle(value = "临停差额",order=18)
    public Double getTempPayDiff() {
        return tempPayDiff;
    }

    public void setTempPayDiff(Double tempPayDiff) {
        this.tempPayDiff = tempPayDiff;
    }
}
